### ISSUE TITLE
Split brain?

### ISSUE THREAD

**Issue by huntc** [typesafehub/project-doc#36]
For some reason, webhook even propogation is not happening - could the project-doc cluster have split-brained?

To reproduce go to: http://conductr.typesafe.com/intro/Manage-Services.html - keep doing so until the url cannot be found. One instance receives the webhook events, the other doesn't.

**Comment by markusjura** [comment]
Could not reproduce this issue. Reloaded the page in two different browsers more than 30 times. Never received a 'url cannot be found'.

Is this maybe a caching problem on your end?

**Comment by huntc** [comment]
Thanks for reminding me... the issue was indeed a split brain on both the ConductR and project-doc clusters. We need to implement split-brain handling for project-doc by using Akka's new downing strategies. I'll retain this issue as a reminder.

**Comment by huntc** [comment]
BTW: We restarted the ConductR service on the node that had become split and all became well.

**Comment by markusjura** [comment]
Can this issue be closed?

**Comment by huntc** [comment]
Yes
