### ISSUE TITLE
Documentation Styles

### ISSUE THREAD

**Issue by rasummer** [typesafehub/project-doc#7]
Refines styles for the documentation pages

**Comment by huntc** [comment]
Does #10 fix this? I will assume so.

Tip: If you declare "fixes #10" in your PR comments then this will auto-close.

**Comment by rasummer** [comment]
Yes, thanks for the tip

**Comment by huntc** [comment]
Unsure about the code styles for this latest commit - are you happy with them?

**Comment by rasummer** [comment]
Didn't change them much yet.  I was wondering why some of the code snippets that span across multiple lines each have there own box around them, rather then one big box. Is that correct? I'll take a look at some of our other doc sites and decide on one to emulate. I'll create a new issue for this.

**Comment by rasummer** [comment]
Ok, I need to style the pre tags as well, will fix and send another PR

**Comment by rasummer** [comment]
OK, sent you a new PR ;)
